name: test

on:
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        builder:
          - 5.3-5:1.15.7-26.2.1-2
        os:
          - ubuntu24.04
    runs-on: ubuntu-latest
    container: ghcr.io/emqx/emqx-builder/${{ matrix.builder }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0

      - name: eunit
        run: make eunit
      - name: ct
        run: make ct
