name: test

on:
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        builder:
          - 5.2-7:1.15.7-26.1.2-1
        os:
          - ubuntu22.04
    runs-on: ubuntu-latest
    container: ghcr.io/emqx/emqx-builder/${{ matrix.builder }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: eunit
        run: make eunit
      - name: ct
        run: make ct
