name: test

on:
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 25.3.2-1
        elixir:
          - 1.14.5
        arch:
          - amd64
        os:
          - ubuntu22.04
    runs-on: ubuntu-latest
    container: ghcr.io/emqx/emqx-builder/5.1-3:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: eunit
        run: make eunit
      - name: ct
        run: make ct
