name: test

on:
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 23.3.4.9-4
          - 24.2.1-1
        elixir:
          - 1.13.3
        arch:
          - amd64
        os:
          - ubuntu20.04
          - rockylinux8
    runs-on: ubuntu-latest
    container: ghcr.io/emqx/emqx-builder/5.0-8:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: eunit
        run: make eunit
      - name: ct
        run: make ct
